parameters:
    parser_specific_configuration:
        utkonos:
            menu:
                name: "categories"
                xpath:
                    group: "//*[@class='module_catalogue_left-header']"
                    to_parse:
                        url: ".//a/@href"
                        name: ".//@title"
                child_page:
                    name: "sub_categories"
                    xpath:
                        group: "//*[@class='module_catalogue_left-child']"
                        to_parse:
                            url: ".//a/@href"
                            name: ".//@title"
                    child_page:
                        name: "product"
                        pagination:
                            to_parse:
                                url: "//*[@class='el_paginate']//span/following-sibling::a[1]/@href"
                        xpath:
                            group: "//*[contains(@class,'goods_view_box')]/div[contains(@class,'goods_view-item')]"
                            to_parse:
                                id: "./@data-item_id"
                                url: ".//*[contains(@class,'goods_view_box-caption')]//a/@href"
                                name: ".//*[contains(@class,'goods_view_box-caption')]//@title"
                                price: ".//@data-static-old-price"
                                price_with_discount: ".//@data-static-now-price"
                                variants_all: ".//*[contains(@class,'goods_variants_property-item')]/span"
                            child_page:
                                name: "product_details"
                                xpath:
                                    to_parse:
                                        description: "//*[@class='goods_view_item-tabs_wrap']//*[@data-tab-link='description']/div"
                                        weight: "//*[@class='goods_view_item-property_item'][child::*[@class='goods_view_item-property_title'][contains(text(),'Вес')]]//@title"
                                        product_type: "//*[@class='goods_view_item-property_item'][child::*[@class='goods_view_item-property_title'][contains(text(),'Тип')]]//@title"
                                        package_type: "//*[@class='goods_view_item-property_item'][child::*[@class='goods_view_item-property_title'][contains(text(),'В упаковк')]]//div[@class='goods_view_item-property_value']"
                                        brand: "//*[@class='goods_view_item-property_item'][child::*[@class='goods_view_item-property_title'][contains(text(),'Бренд')]]//@title"
                                        country: "//*[@class='goods_view_item-property_item'][child::*[@class='goods_view_item-property_title'][contains(text(),'Страна')]]//@title"
                                        lwh: "//*[@class='goods_view_item-property_item'][child::*[@class='goods_view_item-property_title'][contains(text(),'В упаковк')]]//div[@class='goods_view_item-property_value']"
                                        images_all: "//*[@class='goods_view_item-variant_area']//@data-pic-high"
