services:
    guzzle.client:
        class: GuzzleHttp\Client

    parsers.jms.object_builder:
        class: ParserBundle\Internal\ObjectBuilder\JMSObjectBuilder
        arguments:
            - '@jms_serializer'
            - '@logger'

    parsers.repository_factory:
        class: ParserBundle\Entity\Repository\Factory
        arguments:
            - '@doctrine.orm.entity_manager'

    parsers.operation.parse.service:
        class: ParserBundle\Operation\Parse\Service\Service
        arguments:
            - '@parsers.operation.parse.parse_from_website_strategy'
            - '@logger'

    parsers.operation.parse.parse_from_website_strategy:
        class: ParserBundle\Operation\Parse\ParsingStrategy\ParseFromWebsiteStrategy
        arguments:
            - '@parsers.operation.parse.dynamic_data_extractor.html_to_array_data_extractor'
            - '@parsers.protocol'

    parsers.operation.parse.dynamic_data_extractor.html_to_array_data_extractor:
        class: ParserBundle\Operation\Parse\DataExtractor\HtmlToArrayDataExtractor

    parsers.parser_config:
        class: ParserBundle\ParserConfig\ParserConfig
        arguments:
            - '%parser_specific_configuration%'

    parsers.protocol:
        class: ParserBundle\Interaction\Protocol\Protocol
        arguments:
            - '@guzzle.client'
            - '@logger'

    parsers.operation.parse.request_transformer:
        class: ParserBundle\Operation\Parse\Transformer\Request\Transformer
        arguments:
            - '@parsers.repository_factory'
            - '@parsers.parser_config'

    parsers.operation.update.persist_data_service_decorator:
        class: ParserBundle\Operation\Update\Service\PersistDataServiceDecorator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@parsers.repository_factory'
            - '@parsers.operation.update.service'
            - '@logger'

    parsers.operation.update.service:
        class: ParserBundle\Operation\Update\Service\Service
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@parsers.repository_factory'
            - '@parsers.operation.parse.service'
            - '@parsers.operation.update.entity_transformer_factory'
            - '@logger'

    parsers.operation.update.entity_transformer_factory:
        class: ParserBundle\Operation\Update\Transformer\Factory
        arguments:
            -
                categories: 'category'
                sub_categories: 'category'
                product: 'product'